name: Release

on:
    push:
        branches:
        - '**'

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
      
            - name: Install uv
              uses: astral-sh/setup-uv@v5
      
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version-file: ".python-version"

            - name: Release on TestPyPI
              run: |
                uv build
                uv publish --publish-url https://test.pypi.org/legacy/ --trusted-publishing always